# Uncomment the next line to define a global platform for your project
 platform :ios, '14'

target 'RetouchMain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ---- General

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  # Rest
  pod 'RestApiManager'
  pod 'Kingfisher'
  # UI
  pod 'NotificationBannerSwift'

  # ---- RetouchAuth
  target 'RetouchAuth' do
    project '../RetouchAuth/RetouchAuth.xcodeproj'
    workspace '../Retouch.xcworkspace'

    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    # Rest
    pod 'RestApiManager'
    pod 'Kingfisher'
    # UI
    pod 'NotificationBannerSwift'
  end

  # ---- RetouchExamples
  target 'RetouchExamples' do
    project '../RetouchExamples/RetouchExamples.xcodeproj'
    workspace '../Retouch.xcworkspace'

    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    # Rest
    pod 'RestApiManager'
    pod 'Kingfisher'
    # UI
    pod 'NotificationBannerSwift'
  end

  # ---- RetouchMore
  target 'RetouchMore' do
    project '../RetouchMore/RetouchMore.xcodeproj'
    workspace '../Retouch.xcworkspace'

    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    # Rest
    pod 'RestApiManager'
    pod 'Kingfisher'
    # UI
    pod 'NotificationBannerSwift'
  end

  # ---- RetouchHome
  target 'RetouchHome' do
    project '../RetouchHome/RetouchHome.xcodeproj'
    workspace '../Retouch.xcworkspace'

    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    # Rest
    pod 'RestApiManager'
    pod 'Kingfisher'
    # UI
    pod 'NotificationBannerSwift'
  end

  # ---- RetouchCommon
  target 'RetouchCommon' do
    project '../RetouchCommon/RetouchCommon.xcodeproj'
    workspace '../Retouch.xcworkspace'

    # Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Messaging'
    # Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    # Rest
    pod 'RestApiManager'
    pod 'Kingfisher'
    # UI
    pod 'NotificationBannerSwift'
  end

  # ---- RetouchMainTests
  target 'RetouchMainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
